### ISSUE TITLE
Default CLK_FAST is 50 MHz

### ISSUE THREAD

**Issue by Iangitpers** [elehobica/pico_fatfs#3]
In tf_card.c around line 49 the CLK_FAST speed is set to 50MHz. I believe this is unrealistic for most SD cards in SPI mode (~20MHz is max?). It was too fast to function on my wired test setup, I changed it to 100KHz and all my bugs went away.

**Comment by elehobica** [comment]
@Iangitpers Thanks this too.
I agree that CLK_FAST=50MHz could be a little bit aggressive setting while it doesn't make problem on stable performance with my wiring condition and several SD cards I've tested. (see the picture and Benchmark Result on Readme.md).
Generally, it is estimated that SD card and SPI wiring condition affect the frequency to be operated and 20MHz SCLK would be a kind of minimum target we need to achieve when we try to use SD card in SPI mode.
I have added the note about CLK_FAST definition on Readme.md.

I'm not for sure about SD card you used and wiring condition in your enviroment, but if the project only could be run with 100KHz SCLK, I think you're suffered from desperately bad wiring condition or bad SD card.

**Comment by Iangitpers** [comment]
You're absolutely right. I'm sure I could push it further, I just knocked it down for testing and consistent view on the logic analyzer. I'll have a real PCB next week and will follow up with my max speed.

**Comment by Iangitpers** [comment]
Wanted to follow up now that I've done a PCB:

1. RP2040 isn't actually giving 50MHz at 50MHz request. The max speed is 62.5MHz, the next is half of that.

I ran:
`        printf("%u\r\n", spi_init(BP_SPI_PORT, 1 * 1000 * 1000));
        printf("%u\r\n", spi_init(BP_SPI_PORT, 10 * 1000 * 1000));
        printf("%u\r\n", spi_init(BP_SPI_PORT, 30 * 1000 * 1000));
        printf("%u\r\n", spi_init(BP_SPI_PORT, 40 * 1000 * 1000));
        printf("%u\r\n", spi_init(BP_SPI_PORT, 50 * 1000 * 1000));
        printf("%u\r\n", spi_init(BP_SPI_PORT, 60 * 1000 * 1000));
        printf("%u\r\n", spi_init(BP_SPI_PORT, 70 * 1000 * 1000));
`
and the results are:

- 992063 (1mhz requested)
- 8928571 (10mhz) 
- 20833333 (30mhz)
- 31250000 (40mhz)
- 31250000 (50mhz)
- 31250000 (60mhz)
- 62500000 (62.5mhz)

2. The max speed I can run at is 31.25MHz. At 62.5MHz the card becomes de-initialized and does random stuff. 

Adding: de-initialization happens even if I slow down the clock to 31.25MHz to service the SD card, then raise CS and go back to 62.5MHz to service e.g. an LCD. 

The only other reference I found to this issue sharing an SPI bus recommends putting the SD card into SPI mode before anything else happens on the bus, but we already do this. This could be a PCB issue, we're looking into it.

**Comment by elehobica** [comment]
so great to have your follow up with test result. Congratulations for PCB done!

1. Actual frequency of SPI
You're absolutely right. I've confirmed pico-sdk code and following part ```spi_set_baudrate()``` determines the SPI_CLK frequency exactly as you remaked.
https://github.com/raspberrypi/pico-sdk/blob/2062372d203b372849d573f252cf7c6dc2800c0a/src/rp2_common/hardware_spi/spi.c#L41

2. Higher SPI frequency during CS high
I have not tested with LCD on same SPI interface, though I tried to simulate higher SPI_CLK frequency during CS of SD card is high as below in tf_card.c. However, I found nothing illegal happened to SD card function.

```
void deselect (void)
{
	CS_HIGH();		/* Set CS# high */
	xchg_spi(0xFF);	/* Dummy clock (force DO hi-z for multiple slave SPI) */

	spi_set_baudrate(spi, 62.5 * MHZ);  /* Set 62.5MHz clock */
	xchg_spi(0xaa); // dummy access
	xchg_spi(0x55); // dummy access
	FCLK_FAST(); /* Set fast clock */
}
```

**Comment by Iangitpers** [comment]
I imagine it takes more than a few bytes to confuse the card. We're also updating some nasty routing, so fingers crossed. 

A more accurate test may be sending 3*240*320 bytes at full speed, then see if sd card is still happy. I really hope it's a problem on my side, running the LCD at 32 MHz isn't much fun :)
